// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace mTouchPDFReader.Demo {
	// Base type probably should be MonoTouch.UIKit.UIViewController or subclass
	[MonoTouch.Foundation.Register("MainTabbarController")]
	public partial class MainTabbarController {
		
		private MonoTouch.UIKit.UIView __mt_view;
		
		private MonoTouch.UIKit.UITabBarController __mt_tabbarController;
		
		#pragma warning disable 0169
		[MonoTouch.Foundation.Connect("view")]
		private MonoTouch.UIKit.UIView view {
			get {
				this.__mt_view = ((MonoTouch.UIKit.UIView)(this.GetNativeField("view")));
				return this.__mt_view;
			}
			set {
				this.__mt_view = value;
				this.SetNativeField("view", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("tabbarController")]
		private MonoTouch.UIKit.UITabBarController tabbarController {
			get {
				this.__mt_tabbarController = ((MonoTouch.UIKit.UITabBarController)(this.GetNativeField("tabbarController")));
				return this.__mt_tabbarController;
			}
			set {
				this.__mt_tabbarController = value;
				this.SetNativeField("tabbarController", value);
			}
		}
	}
}
